### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by apfnet** [mpawlak2/instalike-instagram-bot#1]
Hello, dear!

I am trying to use your script but an error occurs . Please see the text in bold.

Thank you!

credentials are: "--------" with password "---------"
time periods, total: 360 minutes
from 2016-06-26 20:13:00 to 2016-06-26 20:43:00, minutes: 30.0, active: False, wait for 4 hours
from 2016-06-26 15:31:00 to 2016-06-26 17:23:00, minutes: 112.0, active: True, wait for -1 hours
trying to log in ...
logged in
getting photos from tag LojasPanier...
getting photos from tag penteadododia...
getting photos from tag keune...
getting photos from tag loreal...
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    main()
  File "main.py", line 5, in main
    bot.start()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instabot.py", line 61, in start
    self.like_bot.act()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instalike.py", line 43, in act
    self.instagrams = self.content_manager.get_photos()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\content.py", line 39, in get_photos
    self.repository.merge_photo(photo_instance)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 77, in merge_photo
    self.data_source.execute(sql_query)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 12, in execute
    self.connection.execute(sql_query)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2306, in execute
    self._pq_complete()
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2604, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 532, in raise_server_error
    raise server_error
postgresql.exceptions.NumericRangeError: integer out of range
  CODE: 22003
  LOCATION: File 'int8.c', line 1298, in int84 from SERVER
 **CONTEXT: SQL statement "insert into photos (id, code, width, height, is_ad, likes_count, is_video, display_src, loc)
                values (_id, _code, _width, _height, _is_ad, _likes_count, _is_video, _display_src, _location)"
PL/pgSQL function merge_photo(bigint,integer,integer,character varying,boolean,integer,boolean,boolean,character varying,character varying) line 14 at SQL statement
CONNECTION: [idle]
  client_address: ::1/128
  client_port: 52621
  version: PostgreSQL 9.6beta1, compiled by Visual C++ build 1800, 64-bit
CONNECTOR: [Host] pq://postgres:***@localhost:5432/instamanager
  category: None
DRIVER: postgresql.driver.pq3.Driver**

**Comment by mpawlak2** [comment]
Hey!
Thanks for feedback.

I think the problem was when trying to insert 'bigint' value into 'int' column. Forgot to update that in files. You will have to update your local repo and recreate photos table, there is correct 'create table photos' script now (changed int to bigint). If you still get errors let me know.
