### ISSUE TITLE
Problem with non ascii letters in tag field

### ISSUE THREAD

**Issue by Radren** [mpawlak2/instalike-instagram-bot#11]
Try to use non ascii (cyrillic) letters in tag, obtain the following exception:

    Using default.cfg file.
    WARNING! bot is working whole time, be careful because leaving it running for too long time may          result in blocked account.
    working whole time.
    trying to log in ...
    logged in
    Traceback (most recent call last):
        File "main.py", line 9, in <module>
          main()
        File "main.py", line 5, in main
          bot.start()
        File "C:\Andrey\instalike-instagram-bot-master\instabot.py", line 75, in start
          self.like_bot.act()
        File "C:\Andrey\instalike-instagram-bot-master\instalike.py", line 47, in act
          self.instagrams = self.content_manager.get_photos()
        File "C:\Andrey\instalike-instagram-bot-master\content.py", line 29, in get_photos
          print('getting photos from tag {0}...'.format(tag))
        File "c:\Python35\lib\encodings\cp866.py", line 19, in encode
          return codecs.charmap_encode(input,self.errors,encoding_map)[0]
        UnicodeEncodeError: 'charmap' codec can't encode character '\u0455' in position 27: character maps to <undefined>
+

**Comment by mpawlak2** [comment]
Doesn't seem to be working for me. Anyhow, the problem is with printing these non ascii to terminal, it should be downloading media from correct tags.

**Comment by virginsince1997** [comment]
@mpawlak2 can you make a bot to like feeds , i have a script but doesnt seem to work

**Comment by mpawlak2** [comment]
@virginsince1997 hey, what script do you mean?

**Comment by virginsince1997** [comment]
Javascript using Phantom jS
