### ISSUE TITLE
Column named "biography" in table "users"

### ISSUE THREAD

**Issue by apfnet** [mpawlak2/instalike-instagram-bot#2]
Hi, bro!

Please, look this error:

getting photos from tag loreal...
getting photos from tag laahsenna...
getting photos from tag makingoff...
getting photos from tag diadanoiva...
getting photos from tag wakeupandmakeup...
getting photos from tag hairdo...
getting photos from tag remakeup...
getting photos from tag cabelos_etc...
getting photos from tag universodamaquiagem_oficial...
Traceback (most recent call last):
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 9, in <module>
    main()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 5, in main
    bot.start()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instabot.py", line 61, in start
    self.like_bot.act()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instalike.py", line 43, in act
    self.instagrams = self.content_manager.get_photos()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\content.py", line 45, in get_photos
    self.repository.merge_user(user_instance)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 60, in merge_user
    self.data_source.execute(sql_query)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 12, in execute
    self.connection.execute(sql_query)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2306, in execute
    self._pq_complete()
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2604, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 532, in raise_server_error
    raise server_error
postgresql.exceptions.UndefinedColumnError: column "biography" does not exist

  CODE: 42703

  LOCATION: File 'parse_relation.c', line 3090, in errorMissingColumn from SERVER

  CONTEXT: PL/pgSQL function merge_user(bigint,character varying,boolean,integer,integer,character varying,boolean,character varying,boolean,character varying,integer,boolean,boolean,boolean,character varying) line 16 at SQL statement

  HINT: There is a column named "biography" in table "users", but it cannot be referenced from this part of the query.

  INTERNAL_POSITION: 476

  **INTERNAL_QUERY: insert into users (id, username, has_blocked_viewer, follows_count, followed_by_count, external_url, follows_viewer, profile_pic_url, is_private,

		    full_name, posts_count, blocked_by_viewer, followed_by_viewer, is_verified, biography)

		values (_id, _username, _has_blocked_viewer, _follows_count, _followed_by_count, _external_url, _follows_viewer, _profile_pic_url, _is_private,

		    _full_name, _posts_count, _blocked_by_viewer, _followed_by_viewer, _is_verified, biography)**

CONNECTION: [idle]

  client_address: ::1/128

  client_port: 50197

  version: PostgreSQL 9.6beta1, compiled by Visual C++ build 1800, 64-bit

CONNECTOR: [Host] pq://postgres:***@localhost:5432/instamanager

  category: None

DRIVER: postgresql.driver.pq3.Driver

**Comment by mpawlak2** [comment]
HI!

fixed. Changed 'biography' (column name) to '_biography' (variable), db_setup.sql file

Thanks!!

**Comment by apfnet** [comment]
Thank you!

After the bug "biography" see this:

getting photos from tag makingoff...
getting photos from tag diadanoiva...
getting photos from tag wakeupandmakeup...
getting photos from tag hairdo...
getting photos from tag remakeup...
getting photos from tag cabelos_etc...
getting photos from tag universodamaquiagem_oficial...
validating 19 photos
filtered 19 valid photos out of 19
downloaded 19 valid photos
#######################################
----------------LIKES------------------
total time: 43s
likes: 0
failed likes: 0
estimated likes per hour: 0
next like in: 36s
photos to like: 3
#######################################
---------------FOLLOWS-----------------
total time: 44s
follows: 1
failed follows: 0
unfollows: 0
failed unfollows: 0
estimated follows per hour: 81
estimated unfollows per hour: 0
next follow in: 873s
next unfollow in: -1467118747s
users to follow: 16
users to unfollow: 0
Traceback (most recent call last):
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 9, in <module>
    main()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 5, in main
    bot.start()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instabot.py", line 64, in start
    self.follow_bot.act()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instafollow.py", line 77, in act
    self.unfollow()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instafollow.py", line 61, in unfollow
    self.user_ids_to_unfollow = self.content_manager.get_users_to_unfollow()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\content.py", line 62, in get_users_to_unfollow
    response = self.repository.get_users_to_unfollow()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 98, in get_users_to_unfollow
    proc = self.data_source.prepare_procedure('get_users_to_unfollow()')
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 15, in prepare_procedure
    proc = self.connection.proc(procedure_signature)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2340, in proc
    sp = StoredProcedure(proc_id, self)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 1889, in __init__
    proctup = database.sys.lookup_procedure_rp(str(ident))
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\lib\__init__.py", line 297, in __call__
    return self.method(*args, **kw)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 1675, in first
    db._pq_complete()
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2604, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 532, in raise_server_error
    raise server_error
**postgresql.exceptions.UndefinedFunctionError: function "get_users_to_unfollow()" does not exist**

  CODE: 42883

  LOCATION: File 'regproc.c', line 319, in regprocedurein from SERVER

STATEMENT: [prepared]

  sql_parameter_types: ['pg_catalog.cstring']

  results:

    ('oid' 'pg_catalog.oid', 'proname' 'pg_catalog.name', 'pronamespace' 'pg_catalog.oid', 'proowner' 'pg_catalog.oid', 'prolang' 'pg_catalog.oid', 'procost' 'REAL', 'prorows' 'REAL', 'provariadic' 'pg_catalog.oid', 'protransform' 'pg_catalog.regproc', 'proisagg' 'BOOLEAN', 'proiswindow' 'BOOLEAN', 'prosecdef' 'BOOLEAN', 'proleakproof' 'BOOLEAN', 'proisstrict' 'BOOLEAN', 'proretset' 'BOOLEAN', 'provolatile' 'pg_catalog.char', 'proparallel' 'pg_catalog.char', 'pronargs' 'SMALLINT', 'pronargdefaults' 'SMALLINT', 'prorettype' 'pg_catalog.oid', 'proargtypes' '"pg_catalog"."oidvector"', 'proallargtypes' '"pg_catalog"."_oid"', 'proargmodes' '"pg_catalog"."_char"', 'proargnames' '"pg_catalog"."_text"', 'proargdefaults' '"pg_catalog"."pg_node_tree"', 'protrftypes' '"pg_catalog"."_oid"', 'prosrc' 'pg_catalog.text', 'probin' 'pg_catalog.text', 'proconfig' '"pg_catalog"."_text"', 'proacl' '"pg_catalog"."_aclitem"', '_proid' 'pg_catalog.regproc', 'procedure_id' 'pg_catalog.regprocedure', 'proargtypes' '"pg_catalog"."_oid"', 'composite' 'BOOLEAN')

  statement_id: py:0x4629d10

  string:

    SYMBOL: lookup_procedure_rp

      source:

        SELECT

         pg_proc.oid,

         pg_proc.*,

         pg_proc.oid::regproc AS _proid,

         pg_proc.oid::regprocedure as procedure_id,

         COALESCE(string_to_array(trim(replace(textin(oidvectorout(proargtypes)), ',', ' '), '{}'), ' ')::oid[], '{}'::oid[])

          AS proargtypes,

         (pg_type.oid = 'record'::regtype or pg_type.typtype = 'c') AS composite

        FROM

         pg_catalog.pg_proc LEFT JOIN pg_catalog.pg_type ON (

          pg_proc.prorettype = pg_type.oid

         )
         WHERE pg_proc.oid = regprocedurein($1)

    LIBRARY: C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\lib\libsys.sql

CONNECTION: [idle]

  client_address: ::1/128

  client_port: 50442

  version: PostgreSQL 9.6beta1, compiled by Visual C++ build 1800, 64-bit

CONNECTOR: [Host] pq://postgres:***@localhost:5432/instamanager

  category: None

DRIVER: postgresql.driver.pq3.Driver

**Comment by mpawlak2** [comment]
done
