### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by chinciusan** [mpawlak2/instalike-instagram-bot#25]
I think something changed at Instagram. 
It's not working anymore. 
This is what I get: 
`Trying to log in ...
Logged in
scrapping & validating media...
tag media...
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    main()
  File "main.py", line 6, in main
    bot.start()
  File "/home/pi/Projects/instalike-instagram-bot/instabot.py", line 75, in start
    self.like_bot.act()
  File "/home/pi/Projects/instalike-instagram-bot/instalike.py", line 52, in act
    media = self.content_manager.get_next_media()
  File "/home/pi/Projects/instalike-instagram-bot/content.py", line 34, in get_next_media
    if(not self.scrap_media()):
  File "/home/pi/Projects/instalike-instagram-bot/content.py", line 84, in scrap_media
    response = self.scrap_tag_media() or response
  File "/home/pi/Projects/instalike-instagram-bot/content.py", line 96, in scrap_tag_media
    return self.process_media(tag_media)
  File "/home/pi/Projects/instalike-instagram-bot/content.py", line 112, in process_media
    media_details = self.operation.get_photo_details(media['code'])
  File "/home/pi/Projects/instalike-instagram-bot/operation.py", line 196, in get_photo_details
    return json.loads(response.content.decode('utf-8'))['media']
KeyError: 'media'`

**Comment by vestalux** [comment]
same here:

`
Using default.cfg file.
WARNING! High likes per hour may result in blocked account.
WARNING! bot is working whole time, be careful because leaving it running for too long time may result in blocked account.
working whole time.
Trying to log in ...
Logged in
scrapping & validating media...
tag media...
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    main()
  File "main.py", line 5, in main
    bot.start()
  File "/root/instabot/instabot.py", line 76, in start
    self.like_bot.act()
  File "/root/instabot/instalike.py", line 54, in act
    media = self.content_manager.get_next_media()
  File "/root/instabot/content.py", line 34, in get_next_media
    if(not self.scrap_media()):
  File "/root/instabot/content.py", line 84, in scrap_media
    response = self.scrap_tag_media() or response
  File "/root/instabot/content.py", line 96, in scrap_tag_media
    return self.process_media(tag_media)
  File "/root/instabot/content.py", line 112, in process_media
    media_details = self.operation.get_photo_details(media['code'])
  File "/root/instabot/operation.py", line 195, in get_photo_details
    return json.loads(response.content.decode('utf-8'))['media']
KeyError: 'media'
`

**Comment by mpawlak2** [comment]
thanks for issue, should be working
