### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by chinciusan** [mpawlak2/instalike-instagram-bot#28]
`Trying to log in ...
Logged in
scrapping & validating media...
tag media...
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    main()
  File "main.py", line 6, in main
    bot.start()
  File "/home/pi/Projects/onfilm_bot/instabot.py", line 80, in start
    self.like_bot.act()
  File "/home/pi/Projects/onfilm_bot/instalike.py", line 52, in act
    media = self.content_manager.get_next_media()
  File "/home/pi/Projects/onfilm_bot/content.py", line 34, in get_next_media
    if(not self.scrap_media()):
  File "/home/pi/Projects/onfilm_bot/content.py", line 84, in scrap_media
    response = self.scrap_tag_media() or response
  File "/home/pi/Projects/onfilm_bot/content.py", line 94, in scrap_tag_media
    tag_media = self.operation.get_photos_by_tag(bytag)
  File "/home/pi/Projects/onfilm_bot/operation.py", line 158, in get_photos_by_tag
    return json.loads(response.content.decode('utf-8'))['tag']['media']['nodes']
KeyError: 'tag'`

**Comment by mpawlak2** [comment]
Should be okay.
