### ISSUE TITLE
bruh help me out man! :(

### ISSUE THREAD

**Issue by verobin2237** [mpawlak2/instalike-instagram-bot#29]
\instalike-instagram-bot-master>py main.py
Using default.cfg file.
WARNING! bot is working whole time, be careful because leaving it running for too long time may result in blocked account.
working whole time.
Trying to log in ...
Logged in
scrapping & validating media...
tag media...
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    main()
  File "main.py", line 6, in main
    bot.start()
  File "C:\Users\Robin DebNath\Downloads\instalike-instagram-bot-master\instalike-instagram-bot-master\instabot.py", line 75, in start
    self.like_bot.act()
  File "C:\Users\Robin DebNath\Downloads\instalike-instagram-bot-master\instalike-instagram-bot-master\instalike.py", line 52, in act
    media = self.content_manager.get_next_media()
  File "C:\Users\Robin DebNath\Downloads\instalike-instagram-bot-master\instalike-instagram-bot-master\content.py", line 34, in get_next_media
    if(not self.scrap_media()):
  File "C:\Users\Robin DebNath\Downloads\instalike-instagram-bot-master\instalike-instagram-bot-master\content.py", line 84, in scrap_media
    response = self.scrap_tag_media() or response
  File "C:\Users\Robin DebNath\Downloads\instalike-instagram-bot-master\instalike-instagram-bot-master\content.py", line 94, in scrap_tag_media
    tag_media = self.operation.get_photos_by_tag(bytag)
  File "C:\Users\Robin DebNath\Downloads\instalike-instagram-bot-master\instalike-instagram-bot-master\operation.py", line 158, in get_photos_by_tag
    return json.loads(response.content.decode('utf-8'))['tag']['media']['nodes']
KeyError: 'tag'

**Comment by verobin2237** [comment]
why isnt it working?

**Comment by mpawlak2** [comment]
Hey, will look into this in a sec, thanks for contribution!

**Comment by verobin2237** [comment]
yo its WORKING !! ! thanx thankyou verymuch <3

**Comment by mpawlak2** [comment]
Should be okay
