### ISSUE TITLE
 function register_activity(_type => integer, _user_id => integer, _activity_time => numeric) does not exist

### ISSUE THREAD

**Issue by apfnet** [mpawlak2/instalike-instagram-bot#3]
Traceback (most recent call last):
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 9, in <module>
    main()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 5, in main
    bot.start()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instabot.py", line 65, in start
    self.activity_bot.act()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instaactivity.py", line 38, in act
    self.parse_activities()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instaactivity.py", line 34, in parse_activities
    self.repository.register_activity(activity)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 95, in register_activity
    self.data_source.execute(sql_query)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 12, in execute
    self.connection.execute(sql_query)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2306, in execute
    self._pq_complete()
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2604, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 532, in raise_server_error
    raise server_error
**postgresql.exceptions.UndefinedFunctionError: function register_activity(_type => integer, _user_id => integer, _activity_time => numeric) does not exist**

  CODE: 42883

  LOCATION: File 'parse_func.c', line 523, in ParseFuncOrColumn from SERVER

  HINT: No function matches the given name and argument types. You might need to add explicit type casts.

  POSITION: 8

CONNECTION: [idle]

  client_address: ::1/128

  client_port: 50604

  version: PostgreSQL 9.6beta1, compiled by Visual C++ build 1800, 64-bit

CONNECTOR: [Host] pq://postgres:***@localhost:5432/instamanager

  category: None

DRIVER: postgresql.driver.pq3.Driver

**Comment by mpawlak2** [comment]
fixed: changed register_activity signature to (integer, bigint, double). Please recreate register_activity function

**Comment by apfnet** [comment]
Thank you!
