### ISSUE TITLE
Hi. It stopped working for me

### ISSUE THREAD

**Issue by chinciusan** [mpawlak2/instalike-instagram-bot#34]
`Trying to log in ...
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    main()
  File "main.py", line 6, in main
    bot.start()
  File "/home/pi/Projects/scrise_bot/instabot.py", line 61, in start
    while(not self.log_in()):
  File "/home/pi/Projects/scrise_bot/instabot.py", line 45, in log_in
    response = self.operation.log_in(self.configuration.instagram_username, self.configuration.instagram_password)
  File "/home/pi/Projects/scrise_bot/operation.py", line 46, in log_in
    self.prepare_request(response)
  File "/home/pi/Projects/scrise_bot/operation.py", line 99, in prepare_request
    'x-csrftoken': request_response.cookies['csrftoken'],
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 276, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 331, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"`

**Comment by chnaski** [comment]
#same

**Comment by lcostaracing7** [comment]
same here

**Comment by stevecohenfr** [comment]
same :(

**Comment by ermiyaeskandary** [comment]
From what I can see in the python log, something to do with login is messed
up. Might look into it

**Comment by ermiyaeskandary** [comment]
Domain and path for CSRF token is not mapping - probably Instagram API
change
