### ISSUE TITLE
Error getting users

### ISSUE THREAD

**Issue by chnaski** [mpawlak2/instalike-instagram-bot#35]
```
could not get valid users.
Error getting users.
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    main()
  File "main.py", line 6, in main
    bot.start()
  File "/Users/danny/Downloads/instalike-instagram-bot/instabot.py", line 78, in start
    self.follow_bot.act()
  File "/Users/danny/Downloads/instalike-instagram-bot/instafollow.py", line 79, in act
    self.follow()
  File "/Users/danny/Downloads/instalike-instagram-bot/instafollow.py", line 52, in follow
    if (response.status_code != 200):
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by diogobernini** [comment]
Same issue here.
