### ISSUE TITLE
postgresql.exceptions.UndefinedFunctionError: function like_photo(_photo_id => bigint, _status_code => integer) does not exist

### ISSUE THREAD

**Issue by apfnet** [mpawlak2/instalike-instagram-bot#4]
Traceback (most recent call last):
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 9, in <module>
    main()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 5, in main
    bot.start()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instabot.py", line 61, in start
    self.like_bot.act()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instalike.py", line 54, in act
    self.like(photo)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instalike.py", line 33, in like
    self.repository.like(photo, response.status_code)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 83, in like
    self.data_source.execute(sql_query)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 12, in execute
    self.connection.execute(sql_query)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2306, in execute
    self._pq_complete()
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 2604, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "C:\Users\APF\AppData\Local\Programs\Python\Python35-32\lib\site-packages\postgresql\driver\pq3.py", line 532, in raise_server_error
    raise server_error
postgresql.exceptions.UndefinedFunctionError: function like_photo(_photo_id => bigint, _status_code => integer) does not exist

  CODE: 42883

  LOCATION: File 'parse_func.c', line 523, in ParseFuncOrColumn from SERVER

  HINT: No function matches the given name and argument types. You might need to add explicit type casts.

  POSITION: 8

CONNECTION: [idle]

  client_address: ::1/128

  client_port: 50847

  version: PostgreSQL 9.6beta1, compiled by Visual C++ build 1800, 64-bit

CONNECTOR: [Host] pq://postgres:***@localhost:5432/instamanager

  category: None

DRIVER: postgresql.driver.pq3.Driver

**Comment by mpawlak2** [comment]
please recreate like_photo function ;)

**Comment by apfnet** [comment]
It's working now. Good job buddy!

Thank you!

**Comment by mpawlak2** [comment]
Great. I would suggest using low like & follow options (these in default.cfg are ok), also it is not recommended to run it 24/7 because instagram may get suspicious. If you have any questions email me.

**Comment by apfnet** [comment]
Yes it's true! Thank you for the tips.

I will not abuse the use.

Thank you!
