### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'banned_tags'

### ISSUE THREAD

**Issue by apfnet** [mpawlak2/instalike-instagram-bot#5]
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py 
Traceback (most recent call last):
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 9, in <module>
    main()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 4, in main
    bot = instabot.InstaBot('', '')
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instabot.py", line 19, in __init__
    self.content_manager = content.ContentManager(self.operation, self.repository, self.configuration)
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\content.py", line 12, in __init__
    self.spam_validator = spam.SpamDetector(self.operation, self.repository)
TypeError: __init__() missing 1 required positional argument: 'banned_tags'
>>>

**Comment by mpawlak2** [comment]
Should be ok. Thank you.
