### ISSUE TITLE
connection exception

### ISSUE THREAD

**Issue by Inlife** [mpawlak2/instalike-instagram-bot#6]
Hey,

Sometimes, after running for a while (day or two) program encounters an exception:
```
#######################################
----------------LIKES------------------
total time: 2352s
likes: 595
failed likes: 8
estimated likes per hour: 923
next like in: 62s
photos to like: 4
#######################################
--------------ACTIVITIES---------------
received follows: 6
received likes: 73
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 251, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 251, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    main()
  File "main.py", line 5, in main
    bot.start()
  File "/Users/Inlife/Projects/instalike/instabot.py", line 61, in start
    self.like_bot.act()
  File "/Users/Inlife/Projects/instalike/instalike.py", line 54, in act
    self.like(photo)
  File "/Users/Inlife/Projects/instalike/instalike.py", line 32, in like
    response = self.operation.like(photo.id)
  File "/Users/Inlife/Projects/instalike/operation.py", line 94, in like
    return self.session.post(self.like_url_tmpl.format(photo_id), headers = self.ajx_headers, cookies = self.cookies)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

Maybe this issue can be fixed, and might help someone :3
Thank you!

**Comment by mpawlak2** [comment]
HI! Will look in to this, thanks:)

**Comment by Inlife** [comment]
btw, @mpawlak2 could you please answer following:
i saw an option to help you not get banned
```
[BAN]
# enable it so your account wont be banned NOT WORKING
DoNotGetBanned = False
```
how will it work? 💭 💭 💭
very interesting feature 👍 😄

**Comment by mpawlak2** [comment]
haha actually have no idea right now, it will probably just disable whole functionality to ensure your account stay safe

**Comment by mpawlak2** [comment]
Hey, @Inlife still getting these exceptions?

**Comment by Inlife** [comment]
oh, no, thank you
i was going to close the issue a few day ago but totally forgot about it

it's all good ! 👍

**Comment by mpawlak2** [comment]
Awesome :+1:
