### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by apfnet** [mpawlak2/instalike-instagram-bot#7]
Traceback (most recent call last):
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 9, in <module>
    main()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\main.py", line 5, in main
    bot.start()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instabot.py", line 71, in start
    self.follow_bot.act()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instafollow.py", line 75, in act
    self.unfollow()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\instafollow.py", line 59, in unfollow
    self.user_ids_to_unfollow = self.content_manager.get_users_to_unfollow()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\content.py", line 62, in get_users_to_unfollow
    response = self.repository.get_users_to_unfollow()
  File "D:\Alisson documentos\Scripts\Python\instalike-instagram-bot-master\database.py", line 108, in get_users_to_unfollow
    return proc()
TypeError: 'str' object is not callable

**Comment by mpawlak2** [comment]
Hello, fixed ;]
